export async function GET() {
  // static list; could be pulled from a database in a real app
  const categories = [
    {
      value: "vegetarian",
      label: "Vegetarian",
      items: [
        "Paneer Butter Masala",
        "Shahi Paneer",
        "Mix Veg",
        "Aloo Gobi",
        "Dal Tadka",
        "Dal Makhani",
        "Jeera Rice",
        "Veg Pulao",
        "Steamed Rice",
        "Peas Pulao",
        "Veg Biryani",
        "Lemon Rice",
        "Curd Rice",
        "Tandoori Roti",
        "Butter Naan",
      ],
    },
    {
      value: "non-vegetarian",
      label: "Non-Vegetarian",
      items: [
        "Butter Chicken",
        "Chicken Curry",
        "Mutton Rogan Josh",
        "Keema",
        "Fish Curry",
        "Fish Fry",
        "Egg Curry",
        "Omelett",
      ],
    },
    {
      value: "fast-food",
      label: "Fast Food",
      items: [
        "Veg Burger",
        "Chicken Burger",
        "Margherita",
        "Farmhouse",
        "French Fries",
        "Nuggets",
        "Momos",
        "Spring Roll",
      ],
    },
    {
      value: "cuisine",
      label: "Cuisine",
      items: [
        "Rajma Chawal",
        "Chole Bhature",
        "Dosa",
        "Idli",
        "Sambhar",
        "Golgappa",
        "Pav Bhaji",
      ],
    },
    {
      value: "dessert",
      label: "Dessert & Sweets",
      items: [
        "Gulab Jamun",
        "Rasgulla",
        "Chocolate Cake",
        "Black Forest",
        "Vanilla Ice Cream",
        "Chocolate Ice Cream",
        "Tea",
        "Coffee",
        "Coke",
        "Pepsi",
        "Orange Juice",
        "Mango Shake",
      ],
    },
    {
      value: "eggitarian",
      label: "Eggitarian",
      items: [
        "Boiled eggs",
        "Egg salad",
        "Egg wraps",
        "Egg fried rice",
        "Egg noodles",
        "Egg sandwich",
        "Egg bhurji",
        "Egg drop soup",
      ],
    },
    {
      value: "weather",
      label: "Weather-Based",
      items: [
        "Hot soups",
        "Ramen",
        "Curry or stew",
        "Creamy pasta",
        "Rice + beans",
        "Roasted potatoes",
        "Grilled cheese sandwiches",
        "Summer salad",
      ],
    },
  ];

  return Response.json(categories);
}